include $(TOPDIR)/rules.mk

LUCI_TITLE:=NetTask - Custom Script Manager
LUCI_DEPENDS:=+luci-lib-fs +luci-compat
LUCI_PKGARCH:=all
PKG_VERSION:=2.0.0
PKG_RELEASE:=2

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
